use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::core::models::{
    client::{
        Client, ClientCreateParams, ClientDeleteParams, ClientDescribeParams, ClientFilter,
        ClientListParams, ClientMeta, ClientUpdateParams,
    },
    list::{ListResponseMeta, RequestFilterParams, RequestListOptions},
    workspace::Workspace,
};

// --- ClientDescribeReq ---
#[derive(Deserialize)]
pub struct ClientDescribeReq {
    pub id: Uuid,
    pub workspace_id: Uuid,
}

impl From<ClientDescribeReq> for ClientDescribeParams {
    fn from(value: ClientDescribeReq) -> Self {
        Self {
            id: value.id,
            workspace_id: value.workspace_id,
        }
    }
}

// --- ClientDescribeRes ---
#[derive(Serialize, Debug)]
pub struct ClientDescribeRes {
    pub id: Uuid,
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339::option")]
    pub updated_at: Option<OffsetDateTime>,
}

impl From<Client> for ClientDescribeRes {
    fn from(client: Client) -> Self {
        Self {
            id: client.id,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

// --- ClientCreateReq ---
#[derive(Deserialize)]
pub struct ClientCreateReq {
    pub workspace_id: Uuid,
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
}

impl From<ClientCreateReq> for ClientCreateParams {
    fn from(value: ClientCreateReq) -> Self {
        Self {
            workspace_id: value.workspace_id,
            name: value.name,
            endpoint: value.endpoint,
            description: value.description,
            tags: value.tags,
            meta: value.meta,
        }
    }
}

// --- ClientCreateRes ---
#[derive(Serialize)]
pub struct ClientCreateRes {
    pub id: Uuid,
    pub secret: String,
    pub workspace: Workspace,
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339::option")]
    pub updated_at: Option<OffsetDateTime>,
}

impl From<Client> for ClientCreateRes {
    /// Converts to response DTO. The `secret` field is set to an empty string as a
    /// placeholder, because the service layer does not currently expose the plaintext
    /// secret on the returned `Client` model.
    fn from(client: Client) -> Self {
        Self {
            id: client.id,
            secret: String::new(),
            workspace: client.workspace,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

impl From<(Client, String)> for ClientCreateRes {
    /// Converts to response DTO. The `String` is the raw client secret,
    /// which is generated by the service layer and only ever shown once.
    fn from((client, secret): (Client, String)) -> Self {
        Self {
            id: client.id,
            secret,
            workspace: client.workspace,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

// --- ClientUpdateReq ---
#[derive(Deserialize)]
pub struct ClientUpdateReq {
    pub id: Uuid,
    pub workspace_id: Uuid,
    pub name: Option<String>,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Option<Vec<String>>,
    pub meta: Option<ClientMeta>,
}

impl From<ClientUpdateReq> for ClientUpdateParams {
    fn from(value: ClientUpdateReq) -> Self {
        Self {
            id: value.id,
            workspace_id: value.workspace_id,
            name: value.name,
            endpoint: value.endpoint,
            description: value.description,
            tags: value.tags,
            meta: value.meta,
        }
    }
}

// --- ClientDeleteReq ---
#[derive(Deserialize)]
pub struct ClientDeleteReq {
    pub id: Uuid,
    pub workspace_id: Uuid,
}

impl From<ClientDeleteReq> for ClientDeleteParams {
    fn from(value: ClientDeleteReq) -> Self {
        Self {
            id: value.id,
            workspace_id: value.workspace_id,
        }
    }
}

// --- ClientDeleteRes ---
#[derive(Serialize)]
pub struct ClientDeleteRes {
    pub id: Uuid,
}

// --- ClientRegenerateSecretReq ---
#[derive(Deserialize)]
pub struct ClientRegenerateSecretReq {
    pub id: Uuid,
    pub workspace_id: Uuid,
}

// --- ClientRegenerateSecretRes ---
#[derive(Serialize)]
pub struct ClientRegenerateSecretRes {
    pub id: Uuid,
    pub secret: String,
}

// --- ClientListReq ---
#[derive(Deserialize, Debug)]
pub struct ClientListReq {
    pub workspace_id: Uuid,
    pub filter: Option<RequestFilterParams<ClientFilter>>,
    pub options: Option<RequestListOptions>,
}

impl From<ClientListReq> for ClientListParams {
    fn from(value: ClientListReq) -> Self {
        Self {
            workspace_id: value.workspace_id,
            filter: value.filter,
            options: value.options,
        }
    }
}

// --- ClientListRes ---
#[derive(Serialize, Debug)]
pub struct ClientListRes {
    pub clients: Vec<ClientDescribeRes>,
    pub metadata: ListResponseMeta,
}

// --- ClientValidateReq ---
#[derive(Deserialize)]
pub struct ClientValidateReq {
    pub workspace_id: Uuid,
    pub client_secret: String,
    pub user_token: String,
    pub required_permissions: Vec<String>,
}

// --- ClientValidateRes ---
#[derive(Serialize)]
pub struct ClientValidateRes {
    pub authorized: bool,
}
