use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::core::error::CoreResult;
use crate::core::models::{
    client::{
        Client, ClientCreateParams, ClientDeleteParams, ClientDescribeParams, ClientFilter,
        ClientListParams, ClientMeta, ClientUpdateParams,
    },
    list::{ListResponseMeta, RequestFilterParams, RequestListOptions},
    workspace::Workspace,
};
use crate::core::traits::params::IntoParams;

// --- ClientDescribeReq ---
#[derive(Deserialize)]
pub struct ClientDescribeReq {
    pub id: Uuid,
    #[serde(default)]
    pub workspace_id: Option<Uuid>,
}

impl IntoParams<ClientDescribeParams> for ClientDescribeReq {
    fn into_params(self) -> CoreResult<ClientDescribeParams> {
        Ok(ClientDescribeParams {
            id: self.id,
            workspace_id: self.workspace_id,
        })
    }
}

// --- ClientDescribeRes ---
#[derive(Serialize, Debug)]
pub struct ClientDescribeRes {
    pub id: Uuid,
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339::option")]
    pub updated_at: Option<OffsetDateTime>,
}

impl From<Client> for ClientDescribeRes {
    fn from(client: Client) -> Self {
        Self {
            id: client.id,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

// --- ClientCreateReq ---
#[derive(Deserialize)]
pub struct ClientCreateReq {
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
    #[serde(default)]
    pub workspace_id: Option<Uuid>,
}

impl IntoParams<ClientCreateParams> for ClientCreateReq {
    fn into_params(self) -> CoreResult<ClientCreateParams> {
        Ok(ClientCreateParams {
            workspace_id: self.workspace_id,
            name: self.name,
            endpoint: self.endpoint,
            description: self.description,
            tags: self.tags,
            meta: self.meta,
        })
    }
}

// --- ClientCreateRes ---
#[derive(Serialize)]
pub struct ClientCreateRes {
    pub id: Uuid,
    pub secret: String,
    pub workspace_id: Uuid,
    pub name: String,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub meta: ClientMeta,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339::option")]
    pub updated_at: Option<OffsetDateTime>,
}

impl From<Client> for ClientCreateRes {
    /// Converts to response DTO. The `secret` field is set to an empty string as a
    /// placeholder, because the service layer does not currently expose the plaintext
    /// secret on the returned `Client` model.
    fn from(client: Client) -> Self {
        Self {
            id: client.id,
            secret: String::new(),
            workspace_id: client.workspace_id,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

impl From<(Client, String)> for ClientCreateRes {
    /// Converts to response DTO. The `String` is the raw client secret,
    /// which is generated by the service layer and only ever shown once.
    fn from((client, secret): (Client, String)) -> Self {
        Self {
            id: client.id,
            secret,
            workspace_id: client.workspace_id,
            name: client.name,
            endpoint: client.endpoint,
            description: client.description,
            tags: client.tags,
            meta: client.meta,
            created_at: client.audit.created_at,
            updated_at: client.audit.updated_at,
        }
    }
}

// --- ClientUpdateReq ---
#[derive(Deserialize)]
pub struct ClientUpdateReq {
    pub id: Uuid,
    pub name: Option<String>,
    pub endpoint: Option<String>,
    pub description: Option<String>,
    pub tags: Option<Vec<String>>,
    pub meta: Option<ClientMeta>,
    #[serde(default)]
    pub workspace_id: Option<Uuid>,
}

impl IntoParams<ClientUpdateParams> for ClientUpdateReq {
    fn into_params(self) -> CoreResult<ClientUpdateParams> {
        Ok(ClientUpdateParams {
            id: self.id,
            workspace_id: self.workspace_id,
            name: self.name,
            endpoint: self.endpoint,
            description: self.description,
            tags: self.tags,
            meta: self.meta,
        })
    }
}

// --- ClientDeleteReq ---
#[derive(Deserialize)]
pub struct ClientDeleteReq {
    pub id: Uuid,
    #[serde(default)]
    pub workspace_id: Option<Uuid>,
}

impl IntoParams<ClientDeleteParams> for ClientDeleteReq {
    fn into_params(self) -> CoreResult<ClientDeleteParams> {
        Ok(ClientDeleteParams {
            id: self.id,
            workspace_id: self.workspace_id,
        })
    }
}

// --- ClientDeleteRes ---
#[derive(Serialize)]
pub struct ClientDeleteRes {
    pub id: Uuid,
}

// --- ClientListReq ---
#[derive(Deserialize, Debug)]
pub struct ClientListReq {
    pub filter: Option<RequestFilterParams<ClientFilter>>,
    pub options: Option<RequestListOptions>,
    #[serde(default)]
    pub workspace_id: Option<Uuid>,
}

impl IntoParams<ClientListParams> for ClientListReq {
    fn into_params(self) -> CoreResult<ClientListParams> {
        Ok(ClientListParams {
            workspace_id: self.workspace_id,
            filter: self.filter,
            options: self.options,
        })
    }
}

// --- ClientListRes ---
#[derive(Serialize, Debug)]
pub struct ClientListRes {
    pub clients: Vec<ClientDescribeRes>,
    pub metadata: ListResponseMeta,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_meta() -> ClientMeta {
        ClientMeta {
            schema_version: "1".to_string(),
        }
    }

    #[test]
    fn test_client_describe_req_into_params() {
        let ws_id = Uuid::new_v4();
        let id = Uuid::new_v4();
        let params = ClientDescribeReq { id , workspace_id: Some(ws_id)}.into_params().unwrap();
        assert_eq!(params.id, id);
        assert_eq!(params.workspace_id, Some(ws_id));
    }

    #[test]
    fn test_client_create_req_into_params() {
        let ws_id = Uuid::new_v4();
        let params = ClientCreateReq {
            name: "my-app".to_string(),
            endpoint: Some("https://cb.example.com".to_string()),
            description: Some("desc".to_string()),
            tags: vec!["tag".to_string()],
            meta: sample_meta(),
        workspace_id: Some(ws_id),
        }
        .into_params()
        .unwrap();

        assert_eq!(params.workspace_id, Some(ws_id));
        assert_eq!(params.name, "my-app");
        assert_eq!(params.endpoint.as_deref(), Some("https://cb.example.com"));
        assert_eq!(params.description.as_deref(), Some("desc"));
        assert_eq!(params.tags, vec!["tag".to_string()]);
        assert_eq!(params.meta.schema_version, "1");
    }

    #[test]
    fn test_client_update_req_into_params() {
        let ws_id = Uuid::new_v4();
        let id = Uuid::new_v4();
        let params = ClientUpdateReq {
            id,
            name: Some("renamed".to_string()),
            endpoint: None,
            description: Some("new desc".to_string()),
            tags: None,
            meta: None,
        workspace_id: Some(ws_id),
        }
        .into_params()
        .unwrap();

        assert_eq!(params.id, id);
        assert_eq!(params.workspace_id, Some(ws_id));
        assert_eq!(params.name.as_deref(), Some("renamed"));
        assert!(params.endpoint.is_none());
        assert_eq!(params.description.as_deref(), Some("new desc"));
        assert!(params.tags.is_none());
    }

    #[test]
    fn test_client_delete_req_into_params() {
        let ws_id = Uuid::new_v4();
        let id = Uuid::new_v4();
        let params = ClientDeleteReq { id , workspace_id: Some(ws_id)}.into_params().unwrap();
        assert_eq!(params.id, id);
        assert_eq!(params.workspace_id, Some(ws_id));
    }

    #[test]
    fn test_client_list_req_into_params() {
        let ws_id = Uuid::new_v4();
        let params = ClientListReq {
            filter: None,
            options: None,
        workspace_id: Some(ws_id),
        }
        .into_params()
        .unwrap();
        assert_eq!(params.workspace_id, Some(ws_id));
        assert!(params.filter.is_none());
        assert!(params.options.is_none());
    }

    #[test]
    fn test_client_describe_res_from_client_default() {
        let res = ClientDescribeRes::from(Client::default());
        assert_eq!(res.id, Uuid::nil());
        assert_eq!(res.name, "New Client");
        assert_eq!(res.meta.schema_version, "1");
    }

    #[test]
    fn test_client_create_res_from_client_tuple() {
        let res = ClientCreateRes::from((Client::default(), "plaintext-secret".to_string()));
        assert_eq!(res.secret, "plaintext-secret");
        assert_eq!(res.workspace_id, Uuid::nil());
        assert_eq!(res.name, "New Client");
    }

    #[test]
    fn test_client_create_res_from_client_has_empty_secret() {
        // The plain `From<Client>` form must NOT leak a secret.
        let res = ClientCreateRes::from(Client::default());
        assert_eq!(res.secret, "");
    }
}
